-- 0 = geblokeerd 
-- 1 = inactief
-- 2 = actief
INSERT INTO products (name, description, price, state, create_date) VALUES 
('Wit Brood', 'Een klassiek, zacht brood met een luchtige textuur.', 2.50, 0, CURRENT_TIMESTAMP),
('Volkoren Brood', 'Gezond brood gemaakt van 100% volkoren tarwe voor een volle smaak.', 2.80, 0, CURRENT_TIMESTAMP),
('Baguette', 'Een knapperige Franse stokbrood met een luchtige binnenkant.', 1.80, 0, CURRENT_TIMESTAMP),
('Chocolade Taart', 'Een rijke en romige taart met pure chocolade.', 12.50, 1, CURRENT_TIMESTAMP),
('Appeltaart', 'Traditionele appeltaart met een vleugje kaneel.', 10.00, 1, CURRENT_TIMESTAMP),
('Kaneelbrood', 'Zacht brood met een heerlijke kaneelvulling.', 3.20, 1, CURRENT_TIMESTAMP),
('Croissant', 'Boterachtige, luchtige croissant met een knapperige buitenkant.', 1.50, 1, CURRENT_TIMESTAMP),
('Cupcake', 'Een luchtige cupcake met een zoete topping.', 2.00, 1, CURRENT_TIMESTAMP),
('Boerenbrood', 'Stevig en rustiek brood met een volle smaak.', 3.00, 0, CURRENT_TIMESTAMP),
('Donut', 'Zachte donut met een glazuurlaagje naar keuze.', 1.20, 0, CURRENT_TIMESTAMP),
('Franse Taart', 'Een elegante taart met een romige vulling.', 11.50, 1, CURRENT_TIMESTAMP),
('Speculaas', 'Knapperige koekjes met een rijke kruidige smaak.', 2.10, 1, CURRENT_TIMESTAMP),
('Koffiebroodje', 'Zoet broodje gevuld met banketbakkersroom.', 1.80, 1, CURRENT_TIMESTAMP),
('Brownie', 'Chocoladerijke brownie met een smeuïge textuur.', 3.50, 2, CURRENT_TIMESTAMP),
('Peach Tart', 'Frisse perziktaart met een krokante bodem.', 5.00, 1, CURRENT_TIMESTAMP),
('Zuurdesem', 'Ambachtelijk zuurdesembrood met een licht zure smaak.', 3.30, 2, CURRENT_TIMESTAMP),
('Chocolade Croissant', 'Croissant gevuld met smeuïge chocolade.', 2.50, 0, CURRENT_TIMESTAMP),
('Amandelbrood', 'Luchtig brood met geroosterde amandelen.', 3.00, 1, CURRENT_TIMESTAMP),
('Raisinbrood', 'Brood gevuld met zoete rozijnen.', 2.60, 1, CURRENT_TIMESTAMP),
('Marsepeintaart', 'Luxe taart bedekt met een laag marsepein.', 15.00, 1, CURRENT_TIMESTAMP),
('Lemon Cake', 'Frisse cake met een subtiele citroensmaak.', 4.00, 1, CURRENT_TIMESTAMP),
('Appelflap', 'Bladerdeeg gevuld met appel en kaneel.', 1.90, 0, CURRENT_TIMESTAMP),
('Ragoutbroodje', 'Hartig broodje gevuld met romige ragout.', 2.80, 0, CURRENT_TIMESTAMP),
('Scones', 'Luchtige Britse scones, perfect met jam en room.', 3.10, 1, CURRENT_TIMESTAMP),
('Kruidenbrood', 'Brood met een mix van aromatische kruiden.', 2.70, 1, CURRENT_TIMESTAMP),
('Muffin', 'Smeuïge muffin met een zachte binnenkant.', 1.90, 2, CURRENT_TIMESTAMP),
('Pistolet', 'Krokant broodje met een zachte binnenkant.', 1.40, 1, CURRENT_TIMESTAMP),
('Vlaai', 'Traditionele Limburgse taart met een fruitige vulling.', 8.00, 2, CURRENT_TIMESTAMP),
('Sinaasappelcake', 'Luchtige cake met een frisse sinaasappelsmaak.', 3.30, 1, CURRENT_TIMESTAMP),
('Luchtige Taart', 'Licht en romige taart met een zachte structuur.', 9.00, 2, CURRENT_TIMESTAMP),
('Ciabatta', 'Italiaans brood met een knapperige korst.', 2.20, 1, CURRENT_TIMESTAMP),
('Tiramisu', 'Italiaans dessert met mascarpone en koffie.', 7.50, 0, CURRENT_TIMESTAMP),
('Zeeuwse Bolus', 'Zoet broodje met een laagje kaneelsuiker.', 3.10, 1, CURRENT_TIMESTAMP),
('Meringue', 'Luchtig schuimgebak met een krokante bite.', 2.40, 1, CURRENT_TIMESTAMP),
('Rijsttaart', 'Romige taart met een vulling van rijstpap.', 5.50, 1, CURRENT_TIMESTAMP),
('Prinsesstaart', 'Fraaie taart bedekt met marsepein en room.', 15.00, 0, CURRENT_TIMESTAMP),
('Chocolade Mousse', 'Fluweelzachte mousse van pure chocolade.', 6.00, 1, CURRENT_TIMESTAMP),
('Apfelstrudel', 'Knapperige deegrol gevuld met appel en rozijnen.', 4.80, 2, CURRENT_TIMESTAMP),
('Zwarte Woud Taart', 'Rijke taart met kersen en chocolade.', 12.00, 1, CURRENT_TIMESTAMP),
('Boterkoek', 'Zachte koek met een volle botersmaak.', 3.00, 0, CURRENT_TIMESTAMP),
('Tostibrood', 'Brood perfect voor het maken van tosti’s.', 2.00, 1, CURRENT_TIMESTAMP),
('Pecan Pie', 'Amerikaanse taart met een vulling van pecannoten.', 6.50, 1, CURRENT_TIMESTAMP),
('Worteltaart', 'Smeuïge taart met wortel en kruiden.', 5.00, 2, CURRENT_TIMESTAMP),
('Banaanbrood', 'Gezond brood met een zoete banaansmaak.', 3.20, 1, CURRENT_TIMESTAMP),
('Quiche', 'Hartige taart met kaas en groenten.', 6.00, 1, CURRENT_TIMESTAMP),
('Brownie met Walnoten', 'Brownie met knapperige walnoten.', 3.90, 2, CURRENT_TIMESTAMP),
('Tropical Cake', 'Exotische cake met tropisch fruit.', 4.50, 1, CURRENT_TIMESTAMP),
('Carrot Cake', 'Amerikaanse worteltaart met roomkaasglazuur.', 5.20, 0, CURRENT_TIMESTAMP),
('Scones met Aardbeien', 'Scones met verse aardbeien en room.', 3.60, 1, CURRENT_TIMESTAMP),
('Gluten Vrij Brood', 'Heerlijk brood zonder gluten.', 4.00, 1, CURRENT_TIMESTAMP),
('Pavlova', 'Luchtig dessert met knapperige meringue.', 5.50, 2, CURRENT_TIMESTAMP),
('Flensjes', 'Dunne pannenkoekjes, perfect voor elke gelegenheid.', 2.50, 1, CURRENT_TIMESTAMP),
('Tomatenbrood', 'Brood met een subtiele tomatensmaak.', 3.00, 2, CURRENT_TIMESTAMP),
('Kookbrood', 'Stevig brood perfect voor soepen.', 2.80, 1, CURRENT_TIMESTAMP),
('Vlaamse Wafel', 'Zoete wafel met een lichte textuur.', 1.70, 1, CURRENT_TIMESTAMP),
('Witte chocolade Taart', 'Romige taart met witte chocolade.', 10.00, 0, CURRENT_TIMESTAMP),
('Raisin Croissant', 'Croissant met sappige rozijnen.', 2.10, 2, CURRENT_TIMESTAMP),
('Eclairs', 'Gevulde eclairs met een chocoladeglazuur.', 4.00, 1, CURRENT_TIMESTAMP),
('Koffie Cake', 'Cake met een rijke koffiesmaak.', 5.20, 1, CURRENT_TIMESTAMP),
('Syrup Waffle', 'Zoete wafel met stroopvulling.', 2.80, 0, CURRENT_TIMESTAMP);
